mcpServers:
  mcp-timeserver:
    enable: true
    name: "mcp-timeserver"
    transType: "stdio"
    command: "python3"
    args:
      - "-m"
      - "mcp_simple_timeserver"
  mcp-fetch:
    enable: true
    name: "mcp-fetch"
    transType: "stdio"
    command: "uvx"
    args:
      - "mcp-server-fetch"
