mcpServers:
  mcp-timeserver:
    enable: true
    name: "mcp-timeserver"
    transType: "stdio"
    command: "npx"
    args:
      - "-y"
      - "time-mcp"
  mcp-fetch:
    enable: true
    name: "mcp-fetch"
    transType: "stdio"
    command: "uvx"
    args:
      - "mcp-server-fetch"
